/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Octothorpe;
import javax.swing.*;
/**
 *
 * @author victor
 */
public class OctothorpeVIEW extends javax.swing.JFrame {

    OctothorpeDTO octothorpeDTO = new OctothorpeDTO();
    /**
     * Creates new form OctothorpeVIEW
     */
    public OctothorpeVIEW() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button1 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();
        Player1 = new javax.swing.JLabel();
        Symbol1 = new javax.swing.JLabel();
        WinsPlayer1 = new javax.swing.JLabel();
        Separator1 = new javax.swing.JSeparator();
        Player2 = new javax.swing.JLabel();
        Symbol2 = new javax.swing.JLabel();
        WinsPlayer2 = new javax.swing.JLabel();
        Separator2 = new javax.swing.JSeparator();
        NewGame = new javax.swing.JButton();
        LeaveTheGame = new javax.swing.JButton();
        Tie = new javax.swing.JLabel();
        Separator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Octothorpe");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        Button1.setBackground(new java.awt.Color(0, 0, 0));
        Button1.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        Button1.setForeground(new java.awt.Color(255, 255, 255));
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button4.setBackground(new java.awt.Color(0, 0, 0));
        Button4.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        Button4.setForeground(new java.awt.Color(255, 255, 255));
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        Button7.setBackground(new java.awt.Color(0, 0, 0));
        Button7.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        Button7.setForeground(new java.awt.Color(255, 255, 255));
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button8.setBackground(new java.awt.Color(0, 0, 0));
        Button8.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        Button8.setForeground(new java.awt.Color(255, 255, 255));
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button9.setBackground(new java.awt.Color(0, 0, 0));
        Button9.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        Button9.setForeground(new java.awt.Color(255, 255, 255));
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button5.setBackground(new java.awt.Color(0, 0, 0));
        Button5.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        Button5.setForeground(new java.awt.Color(255, 255, 255));
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button6.setBackground(new java.awt.Color(0, 0, 0));
        Button6.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        Button6.setForeground(new java.awt.Color(255, 255, 255));
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button2.setBackground(new java.awt.Color(0, 0, 0));
        Button2.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        Button2.setForeground(new java.awt.Color(255, 255, 255));
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Button3.setBackground(new java.awt.Color(0, 0, 0));
        Button3.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        Button3.setForeground(new java.awt.Color(255, 255, 255));
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        Panel.setBackground(new java.awt.Color(0, 0, 0));
        Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GAME", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 20), new java.awt.Color(255, 255, 255))); // NOI18N
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setToolTipText("");
        Panel.setName(""); // NOI18N

        Player1.setBackground(new java.awt.Color(0, 0, 0));
        Player1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        Player1.setForeground(new java.awt.Color(255, 255, 255));
        Player1.setText("PLAYER 1");

        Symbol1.setBackground(new java.awt.Color(0, 0, 0));
        Symbol1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        Symbol1.setForeground(new java.awt.Color(255, 255, 255));
        Symbol1.setText("SYMBOL: X");

        WinsPlayer1.setBackground(new java.awt.Color(0, 0, 0));
        WinsPlayer1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        WinsPlayer1.setForeground(new java.awt.Color(255, 255, 255));
        WinsPlayer1.setText("NUMBER OF WINS: 0");

        Player2.setBackground(new java.awt.Color(0, 0, 0));
        Player2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        Player2.setForeground(new java.awt.Color(255, 255, 255));
        Player2.setText("PLAYER 2");

        Symbol2.setBackground(new java.awt.Color(0, 0, 0));
        Symbol2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        Symbol2.setForeground(new java.awt.Color(255, 255, 255));
        Symbol2.setText("SYMBOL: O");

        WinsPlayer2.setBackground(new java.awt.Color(0, 0, 0));
        WinsPlayer2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        WinsPlayer2.setForeground(new java.awt.Color(255, 255, 255));
        WinsPlayer2.setText("NUMBER OF WINS: 0");

        NewGame.setBackground(new java.awt.Color(255, 255, 255));
        NewGame.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        NewGame.setText("NEW GAME");
        NewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameActionPerformed(evt);
            }
        });

        LeaveTheGame.setBackground(new java.awt.Color(255, 255, 255));
        LeaveTheGame.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        LeaveTheGame.setText("LEAVE THE GAME");
        LeaveTheGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaveTheGameActionPerformed(evt);
            }
        });

        Tie.setBackground(new java.awt.Color(0, 0, 0));
        Tie.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        Tie.setForeground(new java.awt.Color(255, 255, 255));
        Tie.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Tie.setText("TIES: 0");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separator2)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Separator3)
                    .addComponent(NewGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(Player2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Symbol2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Separator1)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(Player1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Symbol1))
                                    .addComponent(WinsPlayer1)
                                    .addComponent(WinsPlayer2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(LeaveTheGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Symbol1)
                    .addComponent(Player1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WinsPlayer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player2)
                    .addComponent(Symbol2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WinsPlayer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LeaveTheGame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void PlayerActive(){
        if (octothorpeDTO.isPlayer1Active() == true){
            octothorpeDTO.setPlayer1Active(false);
            octothorpeDTO.setPlayer2Active(true);
        }
        else {
            octothorpeDTO.setPlayer1Active(true);
            octothorpeDTO.setPlayer2Active(false);
        }
        
        PlayerWinner("X");
        PlayerWinner("O");
    }
    
    public void PlayerWinner(String Player){
        
        /*@ LINES */
        
        if (Button1.getText().equals(Player) && 
            Button2.getText().equals(Player) &&
            Button3.getText().equals(Player)){
            
            if (Button1.getText().equals("X")){
                Winner("Player 1");
            }
            else
                Winner("Player 2");
        }
        if (Button4.getText().equals(Player) && 
            Button5.getText().equals(Player) &&
            Button6.getText().equals(Player)){
            
            if (Button4.getText().equals("X")){
                Winner("Player 1");
            }
            else
                Winner("Player 2");
        }
        if (Button7.getText().equals(Player) && 
            Button8.getText().equals(Player) &&
            Button9.getText().equals(Player)){
            
            if (Button7.getText().equals("X")){
                Winner("Player 1");
            }
            else
                Winner("Player 2");
        }
        
        /*@ COLUMNS */
        
        if (Button1.getText().equals(Player) && 
            Button4.getText().equals(Player) &&
            Button7.getText().equals(Player)){
            
            if (Button1.getText().equals("X")){
                Winner("Player 1");
            }
            else
                Winner("Player 2");
        }
        if (Button2.getText().equals(Player) && 
            Button5.getText().equals(Player) &&
            Button8.getText().equals(Player)){
            
            if (Button2.getText().equals("X")){
                Winner("Player 1");
            }
            else
                Winner("Player 2");
        }
        if (Button3.getText().equals(Player) && 
            Button6.getText().equals(Player) &&
            Button9.getText().equals(Player)){
            
            if (Button3.getText().equals("X")){
                Winner("Player 1");
            }
            else
                Winner("Player 2");
        }
        
        /*@ DIAGONS */
        
        if (Button1.getText().equals(Player) && 
            Button5.getText().equals(Player) &&
            Button9.getText().equals(Player)){
            
            if (Button1.getText().equals("X")){
                Winner("Player 1");
            }
            else
                Winner("Player 2");
        }
        if (Button3.getText().equals(Player) && 
            Button5.getText().equals(Player) &&
            Button7.getText().equals(Player)){
            
            if (Button3.getText().equals("X")){
                Winner("Player 1");
            }
            else
                Winner("Player 2");
        }
        
        /*@ TIES */
        
        if (!Button1.getText().equals("") &&
            !Button2.getText().equals("") &&
            !Button3.getText().equals("") &&
            !Button4.getText().equals("") &&
            !Button5.getText().equals("") &&
            !Button6.getText().equals("") &&
            !Button7.getText().equals("") &&
            !Button8.getText().equals("") &&
            !Button9.getText().equals("")){
            
            Winner("Draw");
        }
    }
    
    public void Winner(String PlayerWinner){
        if (PlayerWinner.equals("Player 1")){
            JOptionPane.showMessageDialog(null, "Congratulations, Player 1!");
            octothorpeDTO.setNumberWinner1(1 + octothorpeDTO.getNumberWinner1());
            WinsPlayer1.setText("NUMBER OF WINS: " + octothorpeDTO.getNumberWinner1());
            Clear();
        }
        if (PlayerWinner.equals("Player 2")){
            JOptionPane.showMessageDialog(null, "Congratulations, Player 2!");
            octothorpeDTO.setNumberWinner2(1 + octothorpeDTO.getNumberWinner2());
            WinsPlayer2.setText("NUMBER OF WINS: " + octothorpeDTO.getNumberWinner2());
            Clear();
        }
        if (PlayerWinner.equals("Draw")){
            JOptionPane.showMessageDialog(null, "Tie, Play again!"); 
            octothorpeDTO.setNumberTies(1 + octothorpeDTO.getNumberTies());
            Tie.setText("TIES: " + octothorpeDTO.getNumberTies());
            Clear();
        }
    }
    
    public void Clear(){
        Button1.setText("");
        Button2.setText("");
        Button3.setText("");
        Button4.setText("");
        Button5.setText("");
        Button6.setText("");
        Button7.setText("");
        Button8.setText("");
        Button9.setText("");
        
        octothorpeDTO.setPlayer1Active(true);
        octothorpeDTO.setPlayer2Active(false);
    }
    
    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
        if (octothorpeDTO.isPlayer1Active() == true){
            if (Button1.getText().equals("")){
                Button1.setText("X");
                PlayerActive();
            }
        }
        else {
            if (Button1.getText().equals("")){
                Button1.setText("O");
                PlayerActive();
            }
        }
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        // TODO add your handling code here:
        if (octothorpeDTO.isPlayer1Active() == true){
            if (Button2.getText().equals("")){
                Button2.setText("X");
                PlayerActive();
            }
        }
        else {
            if (Button2.getText().equals("")){
                Button2.setText("O");
                PlayerActive();
            }
        }
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        // TODO add your handling code here:
        if (octothorpeDTO.isPlayer1Active() == true){
            if (Button3.getText().equals("")){
                Button3.setText("X");
                PlayerActive();
            }
        }
        else {
            if (Button3.getText().equals("")){
                Button3.setText("O");
                PlayerActive();
            }
        }
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        // TODO add your handling code here:
        if (octothorpeDTO.isPlayer1Active() == true){
            if (Button4.getText().equals("")){
                Button4.setText("X");
                PlayerActive();
            }
        }
        else {
            if (Button4.getText().equals("")){
                Button4.setText("O");
                PlayerActive();
            }
        }
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        // TODO add your handling code here:
        if (octothorpeDTO.isPlayer1Active() == true){
            if (Button5.getText().equals("")){
                Button5.setText("X");
                PlayerActive();
            }
        }
        else {
            if (Button5.getText().equals("")){
                Button5.setText("O");
                PlayerActive();
            }
        }
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        // TODO add your handling code here:
        if (octothorpeDTO.isPlayer1Active() == true){
            if (Button6.getText().equals("")){
                Button6.setText("X");
                PlayerActive();
            }
        }
        else {
            if (Button6.getText().equals("")){
                Button6.setText("O");
                PlayerActive();
            }
        }
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        // TODO add your handling code here:
        if (octothorpeDTO.isPlayer1Active() == true){
            if (Button7.getText().equals("")){
                Button7.setText("X");
                PlayerActive();
            }
        }
        else {
            if (Button7.getText().equals("")){
                Button7.setText("O");
                PlayerActive();
            }
        }
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        // TODO add your handling code here:
        if (octothorpeDTO.isPlayer1Active() == true){
            if (Button8.getText().equals("")){
                Button8.setText("X");
                PlayerActive();
            }
        }
        else {
            if (Button8.getText().equals("")){
                Button8.setText("O");
                PlayerActive();
            }
        }
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
        // TODO add your handling code here:
        if (octothorpeDTO.isPlayer1Active() == true){
            if (Button9.getText().equals("")){
                Button9.setText("X");
                PlayerActive();
            }
        }
        else {
            if (Button9.getText().equals("")){
                Button9.setText("O");
                PlayerActive();
            }
        }
    }//GEN-LAST:event_Button9ActionPerformed

    private void NewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_NewGameActionPerformed

    private void LeaveTheGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaveTheGameActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LeaveTheGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OctothorpeVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OctothorpeVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OctothorpeVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OctothorpeVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OctothorpeVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton LeaveTheGame;
    private javax.swing.JButton NewGame;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Player1;
    private javax.swing.JLabel Player2;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JSeparator Separator3;
    private javax.swing.JLabel Symbol1;
    private javax.swing.JLabel Symbol2;
    private javax.swing.JLabel Tie;
    private javax.swing.JLabel WinsPlayer1;
    private javax.swing.JLabel WinsPlayer2;
    // End of variables declaration//GEN-END:variables
}
